mod commands;
mod git;
mod orchestrator;
mod claude;
mod config;
mod logging;

pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            commands::project::list_projects,
            commands::project::add_project,
            commands::project::remove_project,
            commands::project::get_current_branch,
            commands::project::set_active_project,
            commands::project::get_active_project,
            commands::git::get_git_status,
            commands::git::get_git_diff,
            commands::git::get_file_diff_content,
            commands::git::git_stage,
            commands::git::git_unstage,
            commands::git::git_stage_all,
            commands::git::git_unstage_all,
            commands::git::git_commit,
            commands::git::git_push,
            commands::git::git_pull,
            commands::git::git_create_branch,
            commands::git::git_switch_branch,
            commands::git::git_list_branches,
            commands::git::git_discard_file,
            commands::git::git_delete_untracked_file,
            commands::git::git_merge,
            commands::git::git_rebase,
            commands::git::git_undo_last_commit,
            commands::git::git_delete_branch,
            commands::git::git_stash,
            commands::git::git_stash_pop,
            commands::git::git_fetch,
            commands::git::git_revert_last_push,
            commands::flow::list_flows,
            commands::flow::get_flow,
            commands::flow::execute_flow,
            commands::claude::generate_slug,
            commands::claude::start_session,
            commands::claude::send_message,
            commands::claude::get_session_status,
            commands::claude::stop_session,
            commands::claude::list_claude_sessions,
            commands::claude::respond_to_permission,
            commands::claude::add_permission_rule,
            commands::claude::run_claude_cli,
            commands::claude::query_claude_status,
            commands::config::get_config,
            commands::config::set_config,
            commands::config::scaffold_shared_repo,
            commands::config::check_for_update,
            commands::worktree::list_worktrees,
            commands::worktree::create_worktree,
            commands::worktree::remove_worktree,
            commands::worktree::clean_worktrees,
            commands::worktree::create_session,
            commands::worktree::list_sessions,
            commands::worktree::close_session,
            commands::worktree::close_all_sessions,
            commands::worktree::get_branches_for_repo,
            commands::worktree::setup_worktree_deps,
            commands::window::open_claude_window,
            commands::window::open_breakout_window,
            commands::window::close_breakout_window,
            commands::filesystem::list_directory_recursive,
            commands::filesystem::read_file_content,
            commands::filesystem::write_file_content,
            commands::filesystem::get_language_stats,
            commands::filesystem::list_claude_commands,
            commands::filesystem::resolve_claude_command,
            commands::logging::log_event,
            commands::logging::get_logs,
            commands::logging::clear_logs,
            commands::account::open_login_window,
            commands::account::fetch_claude_usage,
            commands::account::has_claude_session,
            commands::account::clear_claude_session,
            commands::account::trigger_cli_login,
            commands::account::start_usage_polling,
            commands::account::stop_usage_polling,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
